### ISSUE TITLE
aubo_ros2_driver colcon build failed

### ISSUE THREAD

**Issue by dashuaip** [AuboRobot/aubo_ros2_driver#1]
ros2编译失败，git clone 下载的aubo_description缺少config文件夹，请问应该怎么解决
![image](https://github.com/AuboRobot/aubo_ros2_driver/assets/130347165/9dab1120-0963-4e82-9d9d-6413b74740bb)

**Comment by JI-PENG264** [comment]
该问题已修复，更新一下aubo_description就好了

**Comment by dashuaip** [comment]
> 该问题已修复，更新一下aubo_description就好了

谢谢，但是又出现了新的错误，在已安装tf2和realtime-tools的情况下报错找不到头文件
我使用的是Ubuntu20.04，ros2版本为foxy
![image](https://github.com/AuboRobot/aubo_ros2_driver/assets/130347165/6d00fcdf-b758-4d29-bb28-a8851dd98b9d)

**Comment by JI-PENG264** [comment]
主分支的版本为humble，可以用foxy分支的ros驱动
